### ISSUE TITLE
Unable to create steam account swap desktop shortcut 

### ISSUE THREAD

**Issue by perrintang** [TcNobo/TcNo-Acc-Switcher#160] opened 2022-02-07 06:11 UTC

**Comment by TcNobo** [comment] 2022-02-07 10:44
I can't recreate this myself, it seems to be working normally.
Do you get any errors or anything of that kind? Are you able to record how it doesn't work so I can better understand?

**Comment by iamargelh** [comment] 2022-02-11 03:43
At least Riot account swap desktop shortcut works

**Comment by TcNobo** [comment] 2022-02-14 13:24
I can't recreate this, unfortunately. I'll update this message in a few mins if I can recreate it with Windows 11, but I doubt it (I need to update win11 first).

Are you using Microsoft OneDrive, and syncing your desktop by chance - Or another tool that syncs your desktop? I've had a report about a similar issue with OD.

**Comment by perrintang** [comment] 2022-02-14 14:47
It probably is a Windows 11 problem

**Comment by iamargelh** [comment] 2022-02-15 05:37
I made a clean Windows 11 reinstallation and the problem are still there, i disabled OD and unistalled it.
https://files.catbox.moe/vo39st.gif

**Comment by TcNobo** [comment] 2022-02-15 08:15
So far I'm unable to recreate this on Windows 11... If the problem is new, what was the last version that it worked properly?
I will keep trying for a solution :)

**Comment by iamargelh** [comment] 2022-02-15 08:55
@TcNobo Ok, idk if it was because i was running 4.2 release and it magically worked or because i used right click "Swap to account" instead of login button and then the shortcut function worked.
![image](https://user-images.githubusercontent.com/69566165/154026944-4eab70ce-bc25-4822-9fc4-2747f5ac87a5.png)
@perrintang Try to login a account with right click "Swap to account" , and then try to make a shortcut, if it works that's a bug i guess, if not use 4.2 version. and then tell us what happened.

**Comment by perrintang** [comment] 2022-02-15 08:58
Unfortunately, it still doesn't working

**Comment by iamargelh** [comment] 2022-02-15 08:59
I used the 4.2 portable version an then it worked

**Comment by TcNobo** [comment] 2022-02-18 14:19
If you hit `Ctrl+Shift+I` and go to the `Console` tab, do you see an error flash on the screen to even a second?

This should help get this fixed if there is one... I saw in the video [here](https://youtu.be/7yPSCtdGcKI?t=6) that it flashed quickly, so maybe it encountered an error and refreshed? The error would show in the console for a split second, but easily viewable in a paused recording, or hopefully in the log file: `%AppData%\TcNo Account Switcher\log.txt`

**Comment by kaldigo** [comment] 2022-02-21 21:10
This is the error that shows up and disappears. There is no png in that folder just and svg. I added a png and now it works.
![image](https://user-images.githubusercontent.com/6437691/155026666-e56d1ace-1111-4aa8-9ea7-24d0cc3543d5.png)

**Comment by TcNobo** [comment] 2022-02-22 11:23
Ah, yes, I see. Thanks for the screenshot.
I will work on a patch ASAP, as well as checks to see if it's happening for any other platforms!

**Comment by TcNobo** [comment] 2022-02-22 14:18
I've fixed the issue and reworked it for the better https://github.com/TcNobo/TcNo-Acc-Switcher/commit/1c54865c3ffd39ed9d598224ed3667ca7e95e136. A patch should be out later today.
You can manually place a `Steam.png` file (for example) in `%AppData%\wwwroot\img\platform` to override the image used, or it will use the default `.svg` and skin it using the current theme. For example:

Dracula Cyan (Default):
![DraculaCyan](https://user-images.githubusercontent.com/10319195/155143402-455f48e5-dd71-4b76-a41d-7ae224897a08.png)

Monokai:
![Monokai](https://user-images.githubusercontent.com/10319195/155143388-597f404b-9143-4647-8425-e956834d3603.png)

Old Default:
![OldDefault](https://user-images.githubusercontent.com/10319195/155143393-e65056a2-0580-46b5-a699-ca195cc77c06.png)

Looks great on the desktop
![image](https://user-images.githubusercontent.com/10319195/155148383-d52c11c7-344e-49f4-a29a-d616fd43d496.png)

**Comment by TcNobo** [comment] 2022-02-22 23:23
I'll close this issue for now as it's fixed in the latest update, [2022-02-22_00](https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-02-22_00).

Comment o reply to an email to reopen this issue if you experience further issues.

**Closed by TcNobo** 2022-02-22 23:23 UTC
Labels: bug
