### ISSUE TITLE
Missing Framework

### ISSUE THREAD

**Issue by YassinOdisee** [TcNobo/TcNo-Acc-Switcher#203] opened 2022-04-13 13:01 UTC
I used the installer which automically downloaded all the necessary frameworks. 
After it run itself it told me to download frameworks from: https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime?cid=getdotnetcore
I've downloaded every single one but same message keeps coming up.

**Comment by TcNobo** [comment] 2022-05-09 15:44
Sorry for the late response. This should be fixed with the installer. I'll close this issue for now.
If you are still experiencing this issue download and install the following:
  - WebView 2 Runtime: https://go.microsoft.com/fwlink/p/?LinkId=2124703
  - Navigate here: https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime
    - Click Download x64 under `Run Desktop Apps`
    - Click `Download Hosting Bundle`

Then install all of these. There have been a few issues somewhat caused by Microsoft, so it's had to go from 6.0.3 to 6.0.4. WIth no changes on the download page a lot of users ended up confused by this. Even though it says 6.0, it is 6.0.4, which is what this project needs at the moment.

**Closed by TcNobo** 2022-05-09 15:44 UTC
