### ISSUE TITLE
Issue with beta Version: 2021-06-02_01

### ISSUE THREAD

**Issue by K9Paradox** [TcNobo/TcNo-Acc-Switcher#31] opened 2021-06-02 19:11 UTC
When clicking on Login nothing happens, cannot log into any account using the switcher. I reset settings, and still not working sadly.

**Comment by TcNobo** [comment] 2021-06-02 19:26
Yes, if you're talking about Steam - I'm working on a fix now :)

**Comment by K9Paradox** [comment] 2021-06-02 19:28
All good, yes Steam, probably should have mentioned that. Thanks for the amazing application!

**Comment by TcNobo** [comment] 2021-06-02 19:55
Should be fixed in 2021-06-02_02 (Updated just now). https://github.com/TcNobo/TcNo-Acc-Switcher/commit/b5afa6a2360efa9f26aa6623994ad1f939b60cbd
Let me know if the issue is fixed.

**Comment by TcNobo** [comment] 2021-06-07 15:42
Closing, assuming it's fixed.

**Closed by TcNobo** 2021-06-07 15:42 UTC
