### ISSUE TITLE
Steam account shortcuts not working properly

### ISSUE THREAD

**Issue by Gintas2002** [TcNobo/TcNo-Acc-Switcher#161] opened 2022-02-09 20:38 UTC
So it worked before idk what I did is there may be a service that depends on it?? cause I messed with them before Anyone somewhy it switches account as it should and opens games when pressing on expand game & shortcut selection, but when trying to switch account it doesn't open steam or epic games or anything I have to open it manually

**Comment by TcNobo** [comment] 2022-02-09 21:10
Try [Reinstalling the TcNo Account Switcher](https://github.com/TcNobo/TcNo-Acc-Switcher/wiki/FAQ---More-Info#how-do-i-clean-reinstall-the-tcno-account-switcher). What are the steps you follow to recreate this issue?

**Comment by thomasthielen** [comment] 2022-02-11 00:24
I had the same issue - trying to switch accounts in any way (double click, right click -> swap, etc.) usually didn't work, although it sporadically changed its mind and worked again.
The clean install you proposed fixed it for me.

**Comment by TcNobo** [comment] 2022-02-11 00:32
Awesome.

**Comment by TcNobo** [comment] 2022-02-11 00:35
I see the comment wasn't from the original poster. Well, closing in hopes it works for them too.
Reopen with a comment if it doesn't work *

**Comment by Gintas2002** [comment] 2022-02-11 01:01
> 

Oh shoot, i didnt see the comments sorry, i didnt get the replays in email for some reason even tho i had notifications subscribed here, i still have that issue i tried somewhat uninstall but didnt work, maybe i didnt uninstalled it correctly

**Comment by thomasthielen** [comment] 2022-02-11 15:18
I just had the same problem again. Thing is - I probably know what the cause is.
I have created a Desktop Shortcut for the 'Steam' platform, and by starting it via that shortcut I am unable to change accounts. As soon as I go back to the platform selection and select Steam, it suddenly works.

**Comment by Gintas2002** [comment] 2022-02-11 18:04
> 

nope i have everythih set up corectly its probably has to do with a service or webview

**Comment by TcNobo** [comment] 2022-02-12 20:52
> I just had the same problem again. Thing is - I probably know what the cause is. I have created a Desktop Shortcut for the 'Steam' platform, and by starting it via that shortcut I am unable to change accounts. As soon as I go back to the platform selection and select Steam, it suddenly works.

I'll look into this

**Comment by Gintas2002** [comment] 2022-02-13 04:38
Simply put launchers are not opening

**Comment by Gintas2002** [comment] 2022-02-13 20:21
> > I just had the same problem again. Thing is - I probably know what the cause is. I have created a Desktop Shortcut for the 'Steam' platform, and by starting it via that shortcut I am unable to change accounts. As soon as I go back to the platform selection and select Steam, it suddenly works.
> 
> I'll look into this
> 
> As for Webview or a service? I don't understand what's happening... Can you record the issue?

https://www.youtube.com/watch?v=x6QHra548jo here's a video

**Comment by Gintas2002** [comment] 2022-02-14 17:55
> Go to the `TcNo Account Switcher > Steam > Settings` and make sure that `Run Steam as Admin` is unchecked. This may help. Does `runas.exe "C:\Program Files (x86)\Steam\steam.exe" 1` not work, or something? I have added that fallback I mentioned, and should come with the next update.

oh thank you in worked

**Comment by TcNobo** [comment] 2022-02-16 17:53
With the latest release [2022-02-16](https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-02-16_00), there is now an option in `TcNo Account Switcher > Steam > Settings`.
![image](https://user-images.githubusercontent.com/10319195/154325916-5cdeeafc-34ca-49a8-9a5d-f39bd01a0535.png)
Choose the other start method and things should work properly as mentioned before.

Comment on this issue/reply to this email if you still experience issues, or it hasn't improved.

**Closed by TcNobo** 2022-02-16 17:53 UTC
