### ISSUE TITLE
Account Switcher Requires Password

### ISSUE THREAD

**Issue by vodelYT** [TcNobo/TcNo-Acc-Switcher#19] opened 2021-01-06 12:45 UTC
Hello,

somehow when I want to switch Account I still have to enter a password.

Thanks in advance
Aaron

**Comment by TcNobo** [comment] 2021-01-25 11:17
The program does not interact with any passwords anywhere.
This is on Steam's part.
If you can restart your computer and Steam automatically logs you in, then you can use this software.

Make sure that you always use this to switch accounts, or sign in with new ones (Click the Add New button), as clicking "Change user" or signing out on steam will cause that account to 'forget it's password'.
- Duplicate of #15

**Closed by TcNobo** 2021-01-25 11:17 UTC
