### ISSUE TITLE
Installer forces a restart without warning

### ISSUE THREAD

**Issue by Liam2349** [TcNobo/TcNo-Acc-Switcher#162] opened 2022-02-09 22:33 UTC
Hello, thanks for making this software. I've not had a chance to test it out yet.

At the end of the installation, after downloading the runtimes (for which I felt you had an interesting solution), it restarted my PC. Before I could respond, most applications had been closed.

This is a very bad idea and can lead to loss of work, or deeper system corruptions depending on what is being done at the time. I think this should be classed as a bug.

**Comment by TcNobo** [comment] 2022-02-09 22:41
The installer or updater do not have a call to restart your computer.

This was undoubtedly caused by another program, or (for some reason I've never experienced) one of the official Microsoft installers (C++ 2015-2022, WebView2, ASP.NET Core 6, .NET Desktop Runtime 6) -- But I doubt this would happen automatically. You'll always find a "Click yes to confirm" box if an official Microsoft product requires a restart.

**Comment by Liam2349** [comment] 2022-02-09 22:45
Thanks for the quick response, but I think closing the issue may be premature.

I'm familiar with the Microsoft runtime installers - they always require user interaction. In this case, it seemed your program was capable of clicking the boxes, because they proceeded without me doing anything.

In your console app, I pressed a key to continue downloading runtimes - the .NET 6 desktop runtime and one other, I can't remember which, and I never had to interact with those installers.

Do you know how this occurred?

**Comment by TcNobo** [comment] 2022-02-09 22:46
Oh, no I've found what it is. When using `/passive` or `/quiet` it displays with minimal or no UI, and "no prompts". This makes sense as you can explicitly define `/norestart`.
So yes, It's a bug then ~

Should be fixed in the next release

**Comment by Liam2349** [comment] 2022-02-09 22:48
Great, good find. In my case I only lost a little data, but I recommend treating this as urgent.

I've tried the program now and it seems to work well, so thanks!

**Closed** 2022-02-10 17:00 UTC
Labels: bug

**Comment by Liam2349** [comment] 2022-02-10 17:26
Nice work 👍
