### ISSUE TITLE
Adding new account closes SDA

### ISSUE THREAD

**Issue by SamHoque** [TcNobo/TcNo-Acc-Switcher#95] opened 2021-11-12 00:31 UTC
While the program tries to kill steam, it also kills SDA(Steam Desktop Auth), I think it would be a nice feature to add a check to not kill this program.

**Comment by TcNobo** [comment] 2021-11-21 14:26
Duplicate of #86 . Working on a fix right now.

**Closed by TcNobo** 2021-11-21 14:26 UTC
