### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by revilationer** [TcNobo/TcNo-Acc-Switcher#18] opened 2020-12-03 14:24 UTC
If you can add the feature that which we selected account start in offline mode it would be great

**Comment by emersonjr** [comment] 2020-12-28 21:25
agreed!

**Comment by TcNobo** [comment] 2021-02-11 11:47
This is a planned feature. I'm quite sure it's possible.

**Comment by TcNobo** [comment] 2021-02-11 11:50
Duplicate of #16

**Closed by TcNobo** 2021-02-11 11:50 UTC
Labels: duplicate

**Comment by TcNobo** [comment] 2021-04-07 19:10
This feature is confirmed and is coming in the next release of TcNo Account Switcher. See the above comment for a link to the issue with the information on this topic.
