### ISSUE TITLE
Could you add the rockstar launcher?

### ISSUE THREAD

**Issue by SteezyKane1** [TcNobo/TcNo-Acc-Switcher#232] opened 2022-07-09 21:22 UTC
I want to be able to switch from, my main rockstar account to my alt account quicker.

**Comment by TcNobo** [comment] 2022-07-10 20:33
Duplicate of #221.
This was added (last night in fact) and will ship with the coming update in the next few days.

**Closed by TcNobo** 2022-07-10 20:33 UTC
